service: harys-id
image: ghcr.io/harysiman/harys-id

servers:
  web:
    - YOUR_VPS_IP

proxy:
  ssl: true
  host: harys.space

registry:
  server: ghcr.io
  username: HarysIman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_TO_STDOUT: true

ssh:
  user: ubuntu

volumes:
  - "harys_id_storage:/rails/storage"

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
